
services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_db
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  redis_data:
